version: '3.6'

services:
  database:
    image: postgres:13.3-alpine
    profiles:
      - development
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES__ROOT_PASS
      - POSTGRES_DB=postgres
      - PGDATA=/data
      - APP_USER=speiderapp
      - APP_PASSWORD_FILE=/run/secrets/SPEIDERAPP__DB_PASS
      - APP_DB=speiderapp
    volumes:
      # Data and config is commented out so as to prevent persitence, making it easier to reset
      # - ./.docker/db_dev/temp/data:/data
      # - ./.docker/db_dev/temp/config:/config
      - ./.docker/db_dev/initdb:/docker-entrypoint-initdb.d
    secrets:
      - POSTGRES__ROOT_PASS
      - SPEIDERAPP__DB_PASS
  backend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    profiles:
      - development
    ports:
      - "5000:5000"
    environment:
      - SPEIDERAPP__SECRETS_DIRECTORY=/run/secrets
      - SPEIDERAPP__DB_HOST=database
    working_dir: /source
    volumes:
      - ./:/source
      # Excluding the .docker-directory from the container
      - /source/.docker
      # Excluding compiled files from the container, separating the host (Windows) and container (Linux)
      - /source/bin
      - /source/obj
      - /source/SpeiderappAPI/bin
      - /source/SpeiderappAPI/obj
    command: ["dotnet", "watch", "run", "--project", "SpeiderappAPI", "--environment", "Development"]
    depends_on:
      - database
    secrets:
      - SPEIDERAPP__DB_PASS
  frontend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    profiles:
      - development
    ports:
      - "3000-3001:3000-3001"
    working_dir: /source
    volumes:
      - ./SpeiderappPWA:/source
      # Excluding the .docker-directory from the container
      - /source/.docker
      # Excluding compiled files from the container, separating the host (Windows) and container (Linux)
      - /source/bin
      - /source/obj
      - /source/SpeiderappAPI/bin
      - /source/SpeiderappAPI/obj
    command: [ "dotnet", "watch", "run" ]
secrets:
  POSTGRES__ROOT_PASS:
    file: ./.docker/secrets/POSTGRES__ROOT_PASS
  SPEIDERAPP__DB_PASS:
    file: ./.docker/secrets/SPEIDERAPP__DB_PASS
