// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpeiderappAPI.Models;

namespace SpeiderappAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210521155119_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SpeiderappAPI.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Requirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Requirement");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Requirement");

                    b.HasData(
                        new
                        {
                            Id = -2L,
                            AuthorId = -1L,
                            Description = "Actually chop wood",
                            PublishTime = new DateTime(2021, 5, 21, 17, 51, 18, 866, DateTimeKind.Local).AddTicks(134)
                        });
                });

            modelBuilder.Entity("SpeiderappAPI.Models.RequirementPrerequisite", b =>
                {
                    b.Property<long>("RequirerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequireeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdvisory")
                        .HasColumnType("boolean");

                    b.HasKey("RequirerId", "RequireeId");

                    b.HasIndex("RequireeId");

                    b.ToTable("RequirementPrerequisite");

                    b.HasData(
                        new
                        {
                            RequirerId = -1L,
                            RequireeId = -2L,
                            IsAdvisory = false
                        });
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.TaggedWith", b =>
                {
                    b.Property<long>("BadgeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("BadgeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaggedWiths");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Email = "ocrispe0@jugem.jp",
                            FirstName = "Ozzie",
                            LastName = "Crispe"
                        },
                        new
                        {
                            Id = -2L,
                            Email = "adandye@hexun.com",
                            FirstName = "Aggi",
                            LastName = "Dandy"
                        },
                        new
                        {
                            Id = -3L,
                            Email = "gspottiswood2@psu.com",
                            FirstName = "Gerry",
                            LastName = "Spottiswood"
                        });
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Badge", b =>
                {
                    b.HasBaseType("SpeiderappAPI.Models.Requirement");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Resources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Badge");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            AuthorId = -1L,
                            Description = "This is a cool badge for chucking wood.",
                            PublishTime = new DateTime(2021, 5, 21, 17, 51, 18, 865, DateTimeKind.Local).AddTicks(8195),
                            Image = "3aas!2d=",
                            Resources = new string[0],
                            Title = "Woodchuck"
                        });
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Requirement", b =>
                {
                    b.HasOne("SpeiderappAPI.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.RequirementPrerequisite", b =>
                {
                    b.HasOne("SpeiderappAPI.Models.Requirement", "Requiree")
                        .WithMany("RequireePrerequisites")
                        .HasForeignKey("RequireeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeiderappAPI.Models.Requirement", "Requirer")
                        .WithMany("RequirerPrerequisites")
                        .HasForeignKey("RequirerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requiree");

                    b.Navigation("Requirer");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Tag", b =>
                {
                    b.HasOne("SpeiderappAPI.Models.Category", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.TaggedWith", b =>
                {
                    b.HasOne("SpeiderappAPI.Models.Badge", "Badge")
                        .WithMany("TaggedWiths")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeiderappAPI.Models.Tag", "Tag")
                        .WithMany("TaggedWiths")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Category", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Requirement", b =>
                {
                    b.Navigation("RequireePrerequisites");

                    b.Navigation("RequirerPrerequisites");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Tag", b =>
                {
                    b.Navigation("TaggedWiths");
                });

            modelBuilder.Entity("SpeiderappAPI.Models.Badge", b =>
                {
                    b.Navigation("TaggedWiths");
                });
#pragma warning restore 612, 618
        }
    }
}
